name: "Deploy Statusfy"
on:
  push:
    branches: ["main"]
permissions:
  contents: write
jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Publish the static site to GitHub Pages.
        uses: jamesives/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main